name: club_management_app
description: "A new Flutter project for ClubSphere."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets section with correct spacing
  assets:
    - assets/images/logo.png
    - assets/images/  # Puri folder include karne ke liye