# Generated by Django 4.2.29 on 2026-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='memberships_user_id_790436_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['club'], name='memberships_club_id_e93ba9_idx'),
        ),
    ]
