# Generated by Django 4.2.29 on 2026-03-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_eventregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='memberships_user_id_790436_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='memberships_club_id_e93ba9_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
