# Generated by Django 4.2.29 on 2026-03-29 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0006_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='unique_event_registration_user_event',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership_user_club',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_club_id_6ae675_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_status_8890b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_d_ec8074_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_created_2c88fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='event_regis_event_i_343f8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='event_regis_user_id_c9d271_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='event_regis_status_c16502_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='event_regis_created_cd7605_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='memberships_club_id_e93ba9_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='memberships_user_id_790436_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'club')},
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventregistration',
            table=None,
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='rejection_reason',
        ),
    ]
