# Generated by Django 4.2.29 on 2026-04-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_event_image_url'),
        ('clubs', '0008_notification'),
    ]

    operations = [
    ]
