# Generated by Django 4.2.30 on 2026-04-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_event_image_url'),
        ('clubs', '0008_notification'),
    ]

    operations = [
    ]
