# Generated by Django 4.2.29 on 2026-04-17 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0009_merge_0002_event_image_url_0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuggestionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_suggestion_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_phone', models.CharField(max_length=30)),
                ('suggestion', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='clubs.eventsuggestionpoll')),
            ],
            options={
                'db_table': 'event_suggestions',
                'ordering': ['submitted_at'],
            },
        ),
    ]
