# Generated by Django 4.2.30 on 2026-04-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_0002_event_image_url_0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
