# Generated by Django 4.2.29 on 2026-04-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('apply', 'Apply'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('event', 'Event')], max_length=20),
        ),
    ]
