# Generated by Django 4.2.30 on 2026-06-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_fix_missing_event_status'),
        ('clubs', '0013_alter_notification_user'),
    ]

    operations = [
    ]
